# Generated by Django 3.2.19 on 2023-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recent_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivity',
            name='idOfActivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
