"""
Django settings for feather_ai_project project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5i6s#w-c+3iooks5u*nfrh)x!szt57kf5s^qdd940x!2l9tc7^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'pages',
    'accounts',
    'api',
    'library',
    'long_form_editor',
    'chat_feather',
    'saved_copies',
    'recent_activity',
    'settings',
    'library_template',
    'verification',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '1067911559674-mo29eo7eauu15js9i9mb1f0s0vpo2sdm.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

OTP_TOTP_ISSUER = 'Feather.ia'  # Replace with your desired issuer name


ROOT_URLCONF = 'feather_ai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'feather_ai_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'feather_ai_db',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT =  os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'
STATICFILES_DIRS  = [
    os.path.join(BASE_DIR,'feather_ai_project/static'),
    os.path.join(BASE_DIR,'pages/static'),
    # os.path.join(BASE_DIR ,'accounts/static'),

]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Allow SVG files
ALLOWED_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.svg']

...

# Add SVG to allowed MIME types
import mimetypes
mimetypes.add_type("image/svg+xml", ".svg")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OTP_CODE_LENGTH = 6

OTP_CODE_TIMEOUT = 300 # in seconds (5 minutes)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'kerooadel5@gmail.com'
EMAIL_HOST_PASSWORD = 'axvzoimqktbghrgw'
DEFAULT_FROM_EMAIL = 'kerooadel5@gmail.com'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'accounts.authentication.EmailOTPBackend',
    'django.contrib.auth.backends.ModelBackend',
]
SOCIALACCOUNT_LOGIN_ON_GET=True

LOGIN_REDIRECT_URL = "/library/all/"

UNSPLASH_ACCESS_KEY = 'acO_pe-L9l0CKsmOfi5p2ppC6N0k6A_H2yxX8_-bgac'

GOOGLE_API_KEY = 'AIzaSyBJC3g77500BWL2I76rcgdwW4sSDY-idWo'
GOOGLE_CSE_ID = '4223bc263001c4618'
