# Generated by Django 3.2.19 on 2023-06-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
