# Generated by Django 3.2.19 on 2023-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_feather', '0002_chat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
