# Generated by Django 4.1.7 on 2023-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_accessories_acc_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='price_after_discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
    ]
