# Generated by Django 4.1.3 on 2023-05-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_img_post_index_post_place_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreplay',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReplay',
        ),
    ]
