# Generated by Django 4.1.3 on 2023-05-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_commentreplay_comment_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
