# Generated by Django 4.1.3 on 2023-06-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_body_remove_post_img_remove_post_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='index',
        ),
    ]
