# Generated by Django 4.1.3 on 2023-06-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rateplace",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rateplace",
            unique_together={("user", "place")},
        ),
        migrations.RemoveField(
            model_name="rateplace",
            name="place",
        ),
        migrations.AddField(
            model_name="rateplace",
            name="place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="places.place",
            ),
            preserve_default=False,
        ),
    ]
