# Generated by Django 4.1.3 on 2023-03-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(max_length=255)),
                ('main_Image', models.ImageField(upload_to='places')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.JSONField()),
                ('info', models.TextField()),
                ('location_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_Image', models.ImageField(upload_to='places')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('location', models.JSONField()),
                ('info', models.TextField()),
                ('location_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placecategory'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city'),
        ),
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='place_gallery', to='places.placegallery'),
        ),
    ]
