# Generated by Django 4.1.3 on 2023-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
