# Generated by Django 4.0 on 2023-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='place_gallery', to='places.PlaceGallery'),
        ),
    ]
