# Generated by Django 4.0 on 2023-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
