# Generated by Django 3.2.19 on 2023-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_form_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
