# Generated by Django 3.2.19 on 2023-06-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long_form_editor', '0005_article_library_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='block2',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
