# Generated by Django 4.2.1 on 2023-05-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpstaticdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPStaticDevice',
        ),
    ]
