# Generated by Django 4.1.7 on 2023-03-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hizb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("number_of_ayahs", models.IntegerField()),
                ("revelation_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ayah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("text", models.TextField()),
                (
                    "hizb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayahs",
                        to="islamic.hizb",
                    ),
                ),
                (
                    "juz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ayahs",
                        to="islamic.juz",
                    ),
                ),
                (
                    "surah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="islamic.surah"
                    ),
                ),
            ],
        ),
    ]
