# Generated by Django 4.1.7 on 2023-04-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayah",
            name="ar_number",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
