# Generated by Django 4.1.7 on 2023-04-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0002_ayah_ar_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="hizb",
            name="ar_number",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="juz",
            name="ar_number",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
