# Generated by Django 4.1.7 on 2023-04-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0003_hizb_ar_number_juz_ar_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayah",
            name="ayah_number_in_quraan",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
