# Generated by Django 4.1.7 on 2023-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0004_ayah_ayah_number_in_quraan"),
    ]

    operations = [
        migrations.AddField(
            model_name="surah",
            name="fadluha",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="maeni_asamuha",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="maqsiduha_aleamu",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="munasabatiha",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="sabab_nuzuliha",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="sabab_tasmiatiha",
            field=models.TextField(blank=True, null=True),
        ),
    ]
