# Generated by Django 4.1.7 on 2023-04-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0005_surah_fadluha_surah_maeni_asamuha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surah",
            name="asmawuha",
            field=models.TextField(blank=True, null=True),
        ),
    ]
