# Generated by Django 4.1.7 on 2023-04-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0006_surah_asmawuha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hadeeth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hadeeth", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Hadeeth",
            },
        ),
        migrations.CreateModel(
            name="Stories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Stories",
            },
        ),
        migrations.CreateModel(
            name="StoryContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.CharField(max_length=300)),
                ("video_url", models.URLField()),
                ("video_poster", models.URLField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="islamic.stories",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Story Content",
            },
        ),
    ]
