# Generated by Django 4.1.7 on 2023-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0007_hadeeth_stories_storycontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzkarMasaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Al masaa",
            },
        ),
        migrations.CreateModel(
            name="AzkarSabah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Al sabah",
            },
        ),
    ]
