# Generated by Django 4.1.7 on 2023-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0008_azkarmasaa_azkarsabah"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzkarAfterPray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar After Pray",
            },
        ),
        migrations.CreateModel(
            name="AzkarAzan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Azan",
            },
        ),
        migrations.CreateModel(
            name="AzkarBeforeSleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Before Sleep",
            },
        ),
        migrations.CreateModel(
            name="AzkarFoodAndDrink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Food and Drink",
            },
        ),
        migrations.CreateModel(
            name="AzkarHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Home",
            },
        ),
        migrations.CreateModel(
            name="AzkarKhalaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Khalaa",
            },
        ),
        migrations.CreateModel(
            name="AzkarMosque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Mosque",
            },
        ),
        migrations.CreateModel(
            name="AzkarPray",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Pray",
            },
        ),
        migrations.CreateModel(
            name="AzkarTravel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Travel",
            },
        ),
        migrations.CreateModel(
            name="AzkarWakeUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar WakeUp",
            },
        ),
        migrations.CreateModel(
            name="AzkarWoduaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.TextField()),
                ("repeat", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Azkar Woduaa",
            },
        ),
    ]
