# Generated by Django 4.1.7 on 2023-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0009_azkarafterpray_azkarazan_azkarbeforesleep_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AzkarAzan",
        ),
        migrations.DeleteModel(
            name="AzkarFoodAndDrink",
        ),
        migrations.DeleteModel(
            name="AzkarHome",
        ),
        migrations.DeleteModel(
            name="AzkarKhalaa",
        ),
        migrations.DeleteModel(
            name="AzkarMosque",
        ),
        migrations.DeleteModel(
            name="AzkarTravel",
        ),
        migrations.DeleteModel(
            name="AzkarWoduaa",
        ),
        migrations.RemoveField(
            model_name="azkarpray",
            name="repeat",
        ),
        migrations.RemoveField(
            model_name="azkarpray",
            name="zikr",
        ),
        migrations.AddField(
            model_name="azkarpray",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="azkarpray",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
