# Generated by Django 4.1.7 on 2023-04-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0010_delete_azkarazan_delete_azkarfoodanddrink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuaaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Duaa Type",
            },
        ),
        migrations.CreateModel(
            name="DuaaContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "duaa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="islamic.duaatype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Duaa Content",
            },
        ),
    ]
