# Generated by Django 4.1.7 on 2023-04-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0011_duaatype_duaacontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoqiahShareahType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Roqiah Shareah Type",
            },
        ),
        migrations.CreateModel(
            name="RoqiahShareahContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "roqiah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="islamic.roqiahshareahtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Roqiah Shareah Content",
            },
        ),
    ]
