# Generated by Django 4.1.7 on 2023-04-05 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0012_roqiahshareahtype_roqiahshareahcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sebha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(33),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sebha",
            },
        ),
    ]
