# Generated by Django 4.1.7 on 2023-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0015_arkantypes_arkancontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="arkancontent",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
