# Generated by Django 4.1.7 on 2023-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0017_islamicadvices"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsmaaAllahElhousnaa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Asmaa Allah Elhousnaa",
            },
        ),
    ]
