# Generated by Django 4.1.7 on 2023-04-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0018_asmaaallahelhousnaa"),
    ]

    operations = [
        migrations.CreateModel(
            name="AzkarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zikr", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Azkar Type",
            },
        ),
        migrations.CreateModel(
            name="AzkarContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("repeat", models.IntegerField()),
                (
                    "zikr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="islamic.azkartype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Azkar Content",
            },
        ),
    ]
