# Generated by Django 4.1.7 on 2023-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0019_azkartype_azkarcontent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AzkarAfterPray",
        ),
        migrations.DeleteModel(
            name="AzkarBeforeSleep",
        ),
        migrations.DeleteModel(
            name="AzkarMasaa",
        ),
        migrations.DeleteModel(
            name="AzkarPray",
        ),
        migrations.DeleteModel(
            name="AzkarSabah",
        ),
        migrations.DeleteModel(
            name="AzkarWakeUp",
        ),
    ]
