# Generated by Django 4.1.7 on 2023-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0021_tajweedcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionsAndAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("Answer", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Questions And Answers",
            },
        ),
    ]
