# Generated by Django 4.1.7 on 2023-04-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0023_chathistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="question",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
