# Generated by Django 4.1.7 on 2023-04-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("islamic", "0024_alter_chathistory_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="question",
            field=models.CharField(max_length=500),
        ),
    ]
