# Generated by Django 3.2.19 on 2023-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='outline',
            name='select_individual_outlines',
            field=models.BooleanField(default=False),
        ),
    ]
