# Generated by Django 3.2.19 on 2023-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0003_outline_select_individual_outlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='outline',
            name='sub_topic_text',
            field=models.TextField(null=True),
        ),
    ]
