# Generated by Django 3.2.19 on 2023-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0005_alter_outline_sub_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='outline_name',
            field=models.TextField(),
        ),
    ]
