# Generated by Django 3.2.19 on 2023-06-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0007_rename_outline_name_outline_outlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='outline',
            name='sub_topic_text',
        ),
        migrations.CreateModel(
            name='Suboutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suboutlines', models.TextField()),
                ('subOutlineDescription', models.TextField()),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_template.outline')),
            ],
        ),
    ]
