# Generated by Django 3.2.19 on 2023-06-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0010_alter_article_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
