# Generated by Django 3.2.19 on 2023-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0013_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
