# Generated by Django 3.2.19 on 2023-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0015_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='outlines',
            field=models.ManyToManyField(to='library_template.Outline'),
        ),
    ]
