# Generated by Django 3.2.19 on 2023-06-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0017_delete_outlineorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='outlines',
        ),
    ]
