# Generated by Django 3.2.19 on 2023-06-14 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0021_rename_outlineorder_articleoutline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleOutline',
            new_name='OutlineOrder',
        ),
    ]
