# Generated by Django 3.2.19 on 2023-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0024_auto_20230615_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='outlines',
        ),
        migrations.AddField(
            model_name='article',
            name='new_outlines',
            field=models.ManyToManyField(to='library_template.Outline'),
        ),
        migrations.DeleteModel(
            name='OutlineOrder',
        ),
    ]
