# Generated by Django 3.2.19 on 2023-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0028_alter_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
