# Generated by Django 3.2.19 on 2023-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0031_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubject',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsubject',
            name='generated_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
