# Generated by Django 3.2.19 on 2023-06-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0032_auto_20230616_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsubject',
            old_name='generated_emails',
            new_name='generated_subject',
        ),
    ]
