# Generated by Django 3.2.19 on 2023-06-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0033_rename_generated_emails_emailsubject_generated_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('tone_of_voice', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('num_captions', models.PositiveIntegerField(default=0)),
                ('generated_caption', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_template.project')),
            ],
        ),
    ]
