# Generated by Django 3.2.19 on 2023-06-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0034_socialmediapost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='product_name',
        ),
    ]
