# Generated by Django 3.2.19 on 2023-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_template', '0037_alter_article_outlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
