# Generated by Django 4.1.3 on 2023-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_area"),
        ("fav", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favplaces",
            name="place",
            field=models.ManyToManyField(blank=True, null=True, to="places.place"),
        ),
    ]
