# Generated by Django 4.1.3 on 2023-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_area"),
        ("fav", "0002_alter_favplaces_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favplaces",
            name="place",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="places.place"
            ),
        ),
    ]
