# Generated by Django 4.1.3 on 2023-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fav", "0003_alter_favplaces_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="favplaces",
            name="count_of_fav_places",
            field=models.IntegerField(default=0),
        ),
    ]
