# Generated by Django 4.1.3 on 2023-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fav", "0004_favplaces_count_of_fav_places"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favplaces",
            name="count_of_fav_places",
        ),
    ]
