# Generated by Django 4.0 on 2023-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_gallery'),
        ('fav', '0005_remove_favplaces_count_of_fav_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favplaces',
            name='place',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='places.Place'),
        ),
    ]
