# Generated by Django 4.1.3 on 2023-04-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frm', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=250)),
                ('Note', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=250)),
                ('to', models.CharField(max_length=250)),
                ('transportation', models.CharField(choices=[('TokTok', 'Toctok'), ('Bus', 'Bus'), ('Train', 'Train'), ('ManiBus', 'ManiBus'), ('MicroBus', 'MicroBus'), ('Metor', 'Metor'), ('Bike', 'Bike'), ('OnFood', 'On Food')], max_length=10)),
                ('oreder', models.IntegerField(verbose_name='oreder of transportation')),
                ('placeWay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='place_way', to='roads.placeway')),
            ],
        ),
    ]
