# Generated by Django 4.1.3 on 2023-05-06 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorite_places",
        ),
        migrations.DeleteModel(
            name="LovedPlace",
        ),
    ]
